export enum ErrorCode {
  'BAD_REQUEST' = 'BAD_REQUEST',
  'BAD_USER_INPUT' = 'BAD_USER_INPUT',
  'NOT_FOUND' = 'NOT_FOUND',
  'UNAUTHORIZED' = 'UNAUTHORIZED',
  'FORBIDDEN' = 'FORBIDDEN',
  'NOT_IMPLEMENTED' = 'NOT_IMPLEMENTED',
  'UNKNOWN' = 'UNKNOWN',
}
